# =-=-=-=-=-=-=-=-=-=-=-=-=#
# NovaGuilds Configuration #
#                          #
#         Support          #
#   http://novaguilds.pl   #
#                          #
# =-=-=-=-=-=-=-=-=-=-=-=-=#
#      Time format:        #
#     1y 1d 1h 1m 1s       #
#           =              #
#  One year, one day, one  #
#     hour, one minute     #
#     and one second       #
# =-=-=-=-=-=-=-=-=-=-=-=-=#

#Data storage type
# mysql - MySQL database
# sqlite - Local database
# flat - file based
datastorage:
 primary: mysql
 secondary: flat
mysql:
 host: ""
 port: 3306
 database: ""
 username: ""
 password: ""
 prefix: "novaguilds_"

debug: false
deleteinvalid: false

# =-=-= # =-=-=-= #
# Available langs #
# =-=-= # =-=-=-= #
# en-en # English #
# pl-pl # Polish  #
# de-de # German  #
# zh-cn # Chinese #
# =-=-= # =-=-=-= #
lang:
 name: en-en
 #Use Essentials' locale by default
 overrideessentials: false

usetitles: false

barapi:
 enabled: true
 raidbar: true

tabapi:
 rankprefix: false

tagapi:
 enabled: true
 rankprefix: false

holographicdisplays:
 enabled: true
 refresh: 15m

packets:
 enabled: false

#Save interval
saveinterval: 30m

#after the raid is over and this time the guild will get +1 live
liveregeneration:
 regentime: 48h
 taskinterval: 30m

cleanup:
 enabled: true
 inactivetime: 7d
 interval: 1d
 startupdelay: 30s

aliases:
 guild:
  - g
  - gildia
 create:
  - zaloz
 invite:
  - zapros
 abandon:
  - rozwiaz
 join:
  - dolacz
 leave:
  - opusc

gguicmd:
 g_home: ENDER_PEARL 1 name:Home
 TOP: Sign 1

chat:
 tag: "&a{RANK}&{COLOR}{TAG} &r"
 leaderprefix: "*"
 displaynametags: false
 confirmtimeout: 20s
 tagcolors:
  neutral: "a"
  ally: "5"
  war: "c"
 ally:
  prefix: "!!"
  enabled: true
  colortags: true
  leaderprefix: true
  format: "&6[&5Ally&6] &a{TAG}&8{PLAYERNAME}&6:&r "
  msgprefix: "&6"
 guild:
  prefix: "!"
  enabled: true
  leaderprefix: true
  format: "&6[&7Guild&6] &a{LEADERPREFIX}&8{PLAYERNAME}&6:&r "
  msgprefix: "&6"

raid:
 enabled: true
 minonline: 1
 pointstake: 100
 #progress of raid every second (1.00 = 100s to take life)
 multipler: 1.00

 #time guild has to rest in seconds (24h)
 timerest: 24h

 #Inactive time after which the raid is over. seconds.
 timeinactive: 30s

 #+5% points/money for pvp kill during raid
 pvp:
  bonuspercent:
   money: 5
   points: 5

killing:
 moneyforkill: 5
 moneyforrevenge: 10
 rankpercent: 1
 startpoints: 1000
 cooldown: 10m

guild:
 disabledworlds:
  - world_nether
  - world_the_end

 #New guilds protection
 createprotection: 24h

 homefloor:
  enabled: true
  material: obsidian
 startpoints: 1000
 startmoney: 0
 startlives: 2

 slots:
  start: 10
  max: 50

 #distance from spawn
 fromspawn: 100
 stringcheck:
  enabled: true
  regex: false
  pattern: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789&"
  regexpattern: "[A-Za-z0-9&]*"
 settings:
  tag:
   #colored tags
   color: true
   #length
   min: 2
   max: 6
  name:
   min: 4
   max: 10

 killpoints: 5
 deathpoints: 5

 #/g effect
 effect:
  duration: 2000
  list:
   - JUMP
   - INCREASE_DAMAGE
   - HEAL
 defaultranks:
  member:
   - BLOCK_BREAK
   - BLOCK_PLACE
   - MOB_ATTACK
   - MOB_RIDE
   - MOB_LEASH
   - INTERACT
   - BANK_PAY
   - HOME_TELEPORT
   - VAULT_ACCESS
   - VAULT_PUT
  mayor:
   - BLOCK_BREAK
   - BLOCK_PLACE
   - MOB_ATTACK
   - MOB_RIDE
   - MOB_LEASH
   - INTERACT
   - BANK_PAY
   - HOME_TELEPORT
   - VAULT_ACCESS
   - VAULT_PUT
   - KICK
   - EFFECT
   - INVITE
   - BANK_WITHDRAW
   - PVPTOGGLE
   - BUYSLOT
   - BUYLIFE

#permissions: novaguilds.group.GROUP
#there's no need for admin group. novaguilds.group.admin for all stuff free
groups:
 default: #this is default
  guild:
   home:
    tpdelay: 5
    money: 0
    items: []
   join:
    money: 0
    items: []
   create:
    money: 0
    items:
     - dirt 1
   buylife:
    money: 10
    items:
     - GOLD_BLOCK 1
   buyslot:
    money: 10
    items:
     - GOLD_BLOCK 1
   effect:
    money: 100
    items: []

  region:
   #size (radius) of auto created region (5 = 10x10)
   autoregionsize: 5
   #create price
   createmoney: 100
   #price per block
   ppb: 1

vault:
 enabled: true
 item: CHEST 1 name:&6Guild's_Vault
 denyrelative:
  - HOPPER
 hologram:
  enabled: true
  lines:
   - "[ITEM]GOLD_INGOT 1"
   - "&6Guild's Vault"

 # ------------------------------
 # The Tablist
 # It is available only for 1.8 versions
 # and requires NorthTab plugin as a dependency
 # That plugin can be found in local or remote maven repositories.
 # http://repo.novaguilds.pl/tk/northpl/NorthTab/1.1-INDEV/NorthTab-1.1-INDEV.jar
 # It can be also found in ~/.m2/repository/tk/northpl/NorthTab/
 # if you've compiled the plugin yourself
 # All vars and info is available on the website
 # which is given on the top
 #
 # Players top:
 # By points: {PLAYER_TOP_POINTS_Nx}
 # By KDR (kills/deaths): {PLAYER_TOP_KDR_Nx}
 # Replace 'x' with numbers 1-20 and place lines in the scheme
 # The plugin will do the rest.
tablist:
 enabled: false
 refresh: 30s
 toprow:
  players:
   points: "&6[&2{N}&6] &a{PLAYERNAME} &c{POINTS}"
   kdr: "&6[&2{N}&6] &a{PLAYERNAME} &c{KDR}"
  guilds: "&6[&2{N}&6] &a{GUILDNAME} &c{POINTS}"
 scheme:
  - "{PLAYER_NAME}"
  - "Money: &2{PLAYER_BALANCE}$"
  - "Kills: {PLAYER_KILLS}"
  - "Deaths: {PLAYER_DEATHS}"
  - "KDR: {PLAYER_KDR}"
  - "ChatMode: {PLAYER_CHATMODE}"
  - "SpyMode: {PLAYER_SPYMODE}"
  - "Bypass: {PLAYER_BYPASS}"
  - ""
  - "{SERVER_ONLINE}/{SERVER_MAX}"
  - "{WORLD_NAME}"
  - "{WORLD_SPAWN}"
  - ""
  - "{DATE_DAY}-{DATE_MONTH}-{DATE_YEAR}"
  - "{DATE_HOURS}:{DATE_MINUTES}:{DATE_SECONDS}"
  - ""
  - ""
  - ""
  - ""
  - ""
  - "Name: {GUILD_NAME}"
  - "Tag: {GUILD_TAG}"
  - "{GUILD_PLAYERS_ONLINE}/{GUILD_PLAYERS_MAX}"
  - "Lives: {GUILD_LIVES}"
  - "Progress: {GUILD_RAIDPROGRESS}"
  - "PVP: {GUILD_PVP}"
  - "Money: {GUILD_MONEY}"
  - "Points: {GUILD_POINTS}"
  - "Slots: {GUILD_SLOTS}"
  - "OpenInv: {GUILD_OPENINVITATION}"
  - "{GUILD_TIME_REGEN}"
  - "{GUILD_TIME_REST}"
  - "{GUILD_TIME_CREATED}"
  - "{GUILD_HOME}"
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - "Guild top"
  - ""
  - "{GUILD_TOP_N1}"
  - "{GUILD_TOP_N2}"
  - "{GUILD_TOP_N3}"
  - "{GUILD_TOP_N4}"
  - "{GUILD_TOP_N5}"
  - "{GUILD_TOP_N6}"
  - "{GUILD_TOP_N7}"
  - "{GUILD_TOP_N8}"
  - "{GUILD_TOP_N9}"
  - "{GUILD_TOP_N10}"
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - ""
  - "Players TOP (kdr)"
  - "{PLAYER_TOP_KDR_N1}"
  - "{PLAYER_TOP_KDR_N2}"
  - "{PLAYER_TOP_KDR_N3}"
  - "{PLAYER_TOP_KDR_N4}"
  - "{PLAYER_TOP_KDR_N5}"
  - "{PLAYER_TOP_KDR_N6}"
  - "{PLAYER_TOP_KDR_N7}"
  - "{PLAYER_TOP_KDR_N8}"
  - "{PLAYER_TOP_KDR_N9}"
  - "{PLAYER_TOP_KDR_N10}"

region:
 materials:
  check:
   highlight: DIAMOND_BLOCK
  selection:
   corner: EMERALD_BLOCK
   rectangle: WOOL:14
   invalid: WOOL:15
  resize:
   corner: GOLD_BLOCK
   rectangle: WOOL:6
 autoregion: true
 minsize: 10
 maxsize: 100
 adminautosize: 10
 borderparticles: true
 waterflow: true
 mindistance: 20
 allyinteract: false
 tool: "STICK 1 name:&5NovaGuilds_&6Tool lore:&cLeft_Click_+_SHIFT|&6To_toggle_the_mode|&e****&2Check_Mode&e****|&6Right_click_to_check|&e****&2Select_Mode&e***|&cLeft/Right|&6click_to_select|&6Right_click_a_corner|&6to_resize"

 #commands blocked at region when player is not member and not ally
 # ! cmds have to be lowercase !
 blockedcmds:
  - sethome
  - home
  - back

 denyinteract:
  - WOODEN_DOOR
  - LEVER
  - DISPENSER
  - STONE_BUTTON
  - WOOD_BUTTON
  - DROPPER
  - HOPPER
  - FENCE_GATE
  - REDSTONE_COMPARATOR_OFF
  - REDSTONE_COMPARATOR_ON
  - REDSTONE_REPEATER
  - TRAP_DOOR
  - CHEST
  - ANVIL
  - ENCHANTMENT_TABLE
  - WORKBENCH
  - FURNACE
  - DIODE_BLOCK_ON
  - DIODE_BLOCK_OFF
  - WOOD_PLATE
  - STONE_PLATE
  - IRON_PLATE
  - GOLD_PLATE
  - ENDER_CHEST
  - ENDER_PORTAL_FRAME
  - NOTE_BLOCK
  - JUKEBOX
  - BEACON
  - ITEM_FRAME
  - BREWING_STAND
 denyuse:
  - ITEM_FRAME
 denymobdamage:
  - PIG
  - COW
  - SHEEP
  - HORSE
  - WOLF
  - OCELOT
 denyriding:
  - HORSE