#true=mysql, false=sqlite
usemysql: false
mysql:
 host: 
 port: 
 database: 
 username: 
 password: 
 prefix: novaguilds_

debug: false
lang: en-en
 
tabapi: 
 enabled: true
 colortags: true
 rankprefix: false
 
tagapi: 
 enabled: true
 colortags: true
 rankprefix: false
 allycolor:
  enabled: true
  color: "&5"
 
usevault: true

holographicdisplays:
 enabled: true
 
#Save period in minutes
saveperiod: 10
 
chat:
 ally:
  prefix: "!!"
  enabled: true
  colortags: true
  leaderprefix: true
  format: "&6[&5Ally&6] &a{TAG}&8{PLAYERNAME}&6:&r "
  msgprefix: "&6"
 guild:
  prefix: "!"
  enabled: true
  leaderprefix: true
  format: "&6[&7Guild&6] &8{PLAYERNAME}&6:&r "
  msgprefix: "&6"
 
takeover:
 endercrystal:
  enabled: true
  explosionpower: 50
  #seconds
  time: 100
  #cooldown in seconds
  cooldown: 0.1
  requireguild: false
  requirewar: false
 
raid:
 enabled: true
 minonline: 1
 minonlineenemy: 1
 
killing:
 moneyforkill: 5%
 moneyforrevenge: 10%
 
 
guild:
 tag: "&a{RANK}{TAG} &r"
 startpoints: 1000
 settings:
  tag:
   color: true
   min: 2
   max: 6
  name:
   min: 4
   max: 10
 
 killpoints: 5
 deathpoints: 5
 
 #permissions: novaguilds.group.GROUP
 #there's no need for admin group. novaguilds.group.admin for no items required
 create:
  groups:
   default: #this is default
    money: 0
    items:
     - dirt 1
   vip: #novaguilds.group.vip
    money: 0
    items:
     - cobblestone 5

region:
 #price per block
 pricepb: 1
 createprice: 100
 minsize: 10
 maxsize: 100
 tool:
  item: STICK
  
 denyinteract:
  - WOODEN_DOOR
  - LEVER
  - DISPENSER
  - STONE_BUTTON
  - WOOD_BUTTON
  - DROPPER
  - HOPPER
  - FENCE_GATE
  - REDSTONE_COMPARATOR_OFF
  - REDSTONE_COMPARATOR_ON
  - REDSTONE_REPEATER
  - TRAP_DOOR
  - CHEST
  - ANVIL
  - ENCHANTMENT_TABLE
  - WORKBENCH
  - FURNACE
  - DIODE_BLOCK_ON
  - DIODE_BLOCK_OFF
  - WOOD_PLATE
  - STONE_PLATE
  - IRON_PLATE
  - GOLD_PLATE
  - ENDER_CHEST
  - ENDER_PORTAL_FRAME
  - NOTE_BLOCK
  - JUKEBOX
  - BEACON
 denyuse:
  - LAVA_BUCKET
  - WATER_BUCKET
  - BUCKET
 denymobdamage:
  - PIG
  - COW
  - SHEEP
  - HORSE
  - WOLF
  - OCELOT
 denyriding:
  - HORSE